### ISSUE TITLE
Broken for Puppet <6 due to use of Ruby 2.0+ features

### ISSUE THREAD

**Issue by ananace** [puppetlabs/ruby-pwsh#28]
## Describe the Bug
Releases of this module state support for Puppet <6, while using Ruby features that were introduced in more modern Ruby versions than the one packaged in the Puppet 4 and 5 servers. (1.9)

## Expected Behavior
Catalogs should compile

## Steps to Reproduce
- Install this module
- Try to compile a catalog containing any use of powershell
```puppet
exec { 'echo hello world':
  provider => powershell,
}
```

## Environment
 - Version:
   - Module 0.4.0
   - Puppet 5.3.10
 - Platform CentOS 7.7.1908

**Comment by cdenneen** [comment]
@michaeltlombardi the 0.4.0 release shows support for Puppet4. This needs to be bumped.
