### ISSUE TITLE
Should test on appropriate Ruby versions

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/ruby-pwsh#31]
Currently on tests on Linux on Ruby 2.5.1

However this code will run on 

https://docs.travis-ci.com/user/languages/ruby/#specifying-ruby-versions-and-implementations

JRuby 1.7 (Older Puppet Server)
JRuby 9K (ModernPuppet Server)
MRI Ruby 2.3
MRI Ruby 2.4

As well as Windows Platforms (Appveyor of GH Actions)

Should also add the badges for master platform to easily tell if stuff is broken.

**Comment by Sudrien** [comment]
0.4.1 Fails on require in Ruby 1.9.3 due to
`%i[true false]`

Which is great, when the older syntax of
`[true,false]`
Is actually shorter.

I'll submit a PR after further testing
