### ISSUE TITLE
catalog bloat with dsc

### ISSUE THREAD

**Issue by rismoney** [puppetlabs/ruby-pwsh#337]
If you deploy 100s of the same resources (say user objects), the catalog becomes bloated with seemingly the same powershell code over and over again.

I would think there would be some logic in here, to reuse existing resource logic, and execute it against the parameters?
If this isn't tenable, I am not sure how DSC can scale at all?  I am not understanding how to manage/mitigate this.

**Comment by jordanbreen28** [comment]
@rismoney thanks for raising this. Just checking if you are running your agent in debug mode? The script content should only appear in the logs if that is the case.

**Comment by rismoney** [comment]
Not normally, though this is how I observed it.  Are you implying that when in non-debug mode this is not happening?

**Comment by jordanbreen28** [comment]
@rismoney i believe so yes, admit-tingly its been a while since I've dove in here myself. Maybe if you have some agent logs that could help.

**Comment by jordanbreen28** [comment]
@rismoney we've had a bit of a conversation around this, and we have decided that it is best to output the script content to the logs when an agent is run in debug mode as this is crucial to see how Puppet is applying the DSC configuration under the hood. Although we can see your point regarding the catalog bloat, it is only advisable to run puppet in debug mode when you require verbose output.

Reading between the lines it sounds like you aren't seeing this output when puppet is not run in debug mode here, if this is not the case apologies for the misunderstanding and please do re-open.

**Comment by rismoney** [comment]
you are correct.  so then I guess since the catalog doesn't look so big in cache, 200k, then the slowness is in evaluating each group.
