### ISSUE TITLE
[Documentation] is it possible to use admin-powershell?

### ISSUE THREAD

**Issue by rubyFeedback** [puppetlabs/ruby-pwsh#43]
Hey pogran,

Hope this issue is ok and not too much work. I am referring to the main
README.md.

I just found your gem, have not tested it (I write this here on my linux machine;
my windows machine is a separate laptop which is downstairs).

I recently had a need to install a .msixbundle file. I already tested
it and it works in powershell via:

    Add-AppxPackage

However had I'd like to automate this via ruby, in the event that I
have a fresh setup again or another windows machine.

And this is why I file this - does the gem also work if something
requires admin privileges? Right now I don't know, I have not
tested it, but if you could, perhaps a short subsection or
sentence could be added, to show that this is possible
or is not possible (or not needed)? Thank you for reading,
please feel free to close this issue at any moment in time.

**Comment by michaeltlombardi** [comment]
@rubyFeedback it does - but it will need to be started from a process that already has admin privileges, such as via a scheduled task with elevated permissions; it inherits from the parent process.
