### ISSUE TITLE
Superfluous -Command argument on Linux?

### ISSUE THREAD

**Issue by TomyLobo** [puppetlabs/ruby-pwsh#50]
My OS:
Kubuntu 18.04

My Powershell version:
https://snapcraft.io/powershell
latest/stable:    7.0.3 2020-07-16 (137) 62MB classic

My ruby-pwsh version:
ruby-pwsh (0.5.1)

I found this somewhere in strace:
```
22162 write(103, "\33[91m-File: \33[91mThe term '-File' is not recognized as the name of a cmdlet, function, script file, or operable program.\n", 121) = 121
22162 write(103, "Check the spelling of the name, or if a path was included, verify that the path is correct and try again.\33[0m\n", 110) = 110
```

If I remove the "-Command" argument (by commenting out line 359 in pwsh.rb), it works.

**Comment by TomyLobo** [comment]
Btw, I originally wanted to try out this gem to see if it could marshal the powershell objects to equivalent ruby types, but this appears to not be the case. any plans on doing that?

**Comment by michaeltlombardi** [comment]
Without seeing your ruby code, I'm not sure what happened in the run there - would be happy to take a peek - but in general the way the runner is currently designed is to spin up a PowerShell host and then send command strings to new runspaces in that host; ie the way to load a file is to read it in and pass the string.

As for marshalling back and forth, there's some of that work in the [`Util` module](https://github.com/puppetlabs/ruby-pwsh/blob/main/lib/pwsh/util.rb) - coming _back_ from PowerShell though the only sensible thing I have found possible to send back JSON from PowerShell and then parse and handle from there - this is done in the [DSC base provider, for example](https://github.com/puppetlabs/ruby-pwsh/blob/main/lib/puppet/provider/dsc_base_provider/dsc_base_provider.rb#L169-L172).

**Comment by TomyLobo** [comment]
The -File is from your code, not mine.
It's coming from line 133 in pwsh.rb

**Comment by michaeltlombardi** [comment]
Can you share what your actual ruby code that is calling the manager though? We make a template and call it at [L133](https://github.com/puppetlabs/ruby-pwsh/blob/main/lib/pwsh.rb#L133) based on the string being passed, but without knowing what the rest of your implementation looks like and/or the full stack trace I'm not very capable of debugging.

**Comment by TomyLobo** [comment]
I don't have that code here right now, but I read template_path as generating a path that points to a file in the gem, not my code.
I feel like I'm explaining your own code to you here :)
Just try it once and you'll see that it won't be able to start up the powershell backend unless you remove that -Command.
This code isn't there for Windows Powershell, I guess it's no longer needed on linux either now.

**Comment by michaeltlombardi** [comment]
The reason I try to ask for a detailed repro is so I can chase down exactly what's going on. Testing locally, I'm able to instantiate a manager and execute code:

```
root@LAPTOP-OKCNCL0V:/mnt/c/code/puppetlabs/gems/ruby-pwsh# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
root@LAPTOP-OKCNCL0V:/mnt/c/code/puppetlabs/gems/ruby-pwsh# pwsh --version
PowerShell 7.0.3
root@LAPTOP-OKCNCL0V:/mnt/c/code/puppetlabs/gems/ruby-pwsh# bundle exec irb
irb(main):001:0> require 'ruby-pwsh'
=> true
irb(main):002:0> pwsh = Pwsh::Manager.instance(Pwsh::Manager.pwsh_path, Pwsh::Manager.pwsh_args)
=> #<Pwsh::Manager:0x00007fffe56193c8 @usable=true, @powershell_command="/usr/bin/pwsh", @powershell_arguments=["-NoProfile", "-NonInteractive", "-NoLogo", "-ExecutionPolicy", "Bypass"], @stdout=#<IO:fd 11>, @stderr=#<IO:fd 13>, @ps_process=#<Process::Waiter:0x00007fffe54c9d38 sleep>, @pipe=#<UNIXSocket:fd 9>>
irb(main):003:0> pp pwsh.execute('$PSVersionTable')
{:exitcode=>0,
 :stdout=>
  "\n" +
  "Name                           Value\n" +
  "----                           -----\n" +
  "PSVersion                      7.0.3\n" +
  "PSEdition                      Core\n" +
  "GitCommitId                    7.0.3\n" +
  "OS                             Linux 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020\n" +
  "Platform                       Unix\n" +
  "PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}\n" +
  "PSRemotingProtocolVersion      2.3\n" +
  "SerializationVersion           1.1.0.1\n" +
  "WSManStackVersion              3.0\n" +
  "\n",
 :stderr=>[],
 :errormessage=>nil,
 :native_stdout=>nil}
```

If you could provide me with the ruby code you specified to generate the initial stack trace that would be super helpful, thanks! :)

**Comment by TomyLobo** [comment]
argh, i was using `posh = Pwsh::Manager.instance(Pwsh::Manager.powershell_path, Pwsh::Manager.powershell_args)`. i did not realize there was a difference between the first 2 calls and the 3rd in the example in README.md.

**Comment by michaeltlombardi** [comment]
The manager does not currently munge anything you send back; the most compatible way to send back data is to do something like this:

```ruby
# You may want to specify the Depth parameter on ConvertTo-Json
# Sometimes the default depth isn't enough.
jsony = pwsh.execute('$PSVersionTable | ConvertTo-Json -Compress')
structured_output = JSON.parse(jsony[:stdout])
```

**Comment by TomyLobo** [comment]
Can confirm, it works with pwsh_path/args.
However, I still can't use this for what I originally intended to use it for.
Basically what I want to do is Connect-VIServer in one call, then use that in the next.
For some reason the variables (even global ones) required by that function are gone by the next "pwsh.execute".
Is there any way to fix that?
```ruby
$ bundle exec irb
irb(main):001:0> require 'ruby-pwsh'
=> true

irb(main):002:0> pwsh = Pwsh::Manager.instance(Pwsh::Manager.pwsh_path, Pwsh::Manager.pwsh_args)
=> #<Pwsh::Manager:0x000055a62cfaccb0 @usable=true, @powershell_command="/snap/bin/pwsh", @powershell_arguments=["-NoProfile", "-NonInteractive", "-NoLogo", "-ExecutionPolicy", "Bypass"], @stdout=#<IO:fd 11>, @stderr=#<IO:fd 13>, @ps_process=#<Process::Waiter:0x000055a62ce777a0 sleep>, @pipe=#<UNIXSocket:fd 9>>

irb(main):003:0> pwsh.execute('$global:foo = "123"; Write-Host $global:foo')
=> {:stdout=>"123\n", :errormessage=>nil, :stderr=>[], :exitcode=>0, :native_stdout=>nil}

irb(main):004:0> pwsh.execute('Write-Host $global:foo')
=> {:stdout=>"\n", :errormessage=>nil, :stderr=>[], :exitcode=>0, :native_stdout=>nil}
```

**Comment by michaeltlombardi** [comment]
@nmaludy actually has been working on this problem himself and has come to a resolution that includes caching the connection using info from [this blog post by Chris Wahl](https://wahlnetwork.com/2015/12/16/using-previously-connected-vcenter-sessions-with-powercli/), though he's doing it in the context of a puppet run whereas I don't think you are (without seeing the implementation I don't yet know how much difference that makes).

What you're running into is that we're running code via the [custom function `Invoke-PowerShellUserCode`](https://github.com/puppetlabs/ruby-pwsh/blob/f9c3f8efc128ce0526b36ce7aa3952549f3fd789/lib/templates/init.ps1#L381) which adds some safety and custom handling and which currently specifically tries to avoid prior-execution pollution.

What you _might_ consider doing instead is invoking a multi-line script instead of passing things back and forth between languages, and just handle the final output/results in Ruby. Without knowing more about your use case / goals though that's the most useful thing I can think of offhand.

**Comment by TomyLobo** [comment]
Well I wanna connect once on startup (or lazily) and then handle web requests with the existing vcenter connection.
Chris Wahl can cache connections because he's not using ruby-pwsh.
ruby-pwsh gives me a pristine environment each time I .execute, so I can't cache anything at all.

**Comment by michaeltlombardi** [comment]
@nmaludy doesn't have a PR up for his work yet so I can't point you at an example of doing this, only relay his verbal confirmation that he was able to cache and improve his execution timings for exactly that scenario (though, again, in the context of a Puppet run).

**Comment by nmaludy** [comment]
I don't have this coded up yet publicly but let me describe what i'm doing from a high-level. Expect a blog post and public code later this week.

```
class PowerCLI
  def initialize(server, username, password)
    @server = server
    @username = username
    @password = password
  end

  def ps(cmd)
    @ps ||= Pwsh::Manager.instance(Pwsh::Manager.powershell_path, Pwsh::Manager.powershell_args)
    Puppet.debug("Running command: #{cmd}")
    Puppet.debug("@@ps instance id: #{@@ps.object_id}")
    # need to use [:stdout] from result
    @ps.execute(cmd)
  end

  def connect_cmd()
    # check if we have connected before (aka if we have a cached session)
    if @session_id.nil?
      # our session is nil, so we need to conenct
      session_cmd = <<-EOF
$session = Connect-VIServer -Server '#{@server}' -Username '#{@username}' -Password '#{@password}'
$session.SessionId
EOF
      resp = ps(session_cmd)
      # remove quotes from the session id string, it returns us something in the format of:
      #  "abc123"
      # we strip because it returns us some new lines and white space in there as well
      @session_id = resp[:stdout].gsub(/"/, '').strip
    end
    # reconnect with our session
    <<-EOF
Connect-VIServer -Server '#{server}' -Session '#{@session_id}' | Out-Null
EOF
  end
  
  def connect_and_exec(cmd)
    ps(connect_cmd + cmd)
  end
end

# you can then use this like so
pcli = PowerCLI.new('vcenter.domain.tld', 'user', 'pass')
pcli.connect_and_exec('Get-VMHost')
```

Sorry, i'm pulling code from a couple different places here, but the bones should be good.

Basically caching the session id in a class variable and returning a connection string with that cached session as part of it.

This class wraps the logic of connecting initially and storing that cached session, then reusing the cached session on subsequent calls.

**Comment by nmaludy** [comment]
FYI here is the PR we're working on for caching PowerCLI sessions: https://github.com/EncoreTechnologies/puppet-powercli/pull/16/files#diff-48a50b1e7b0fe017bff72006cef23fd7c1f74f038f945c4fbb722ca5fa4be662

Hopefully that helps?

**Comment by michaeltlombardi** [comment]
I'm going to go ahead and close this issue for now - if there's a specific feature request or bug report, please open a new issue to address that explicitly. Glad for the conversation and knowledge sharing that happened here, thanks y'all!
