### ISSUE TITLE
xWebAdministration xIisLogging

### ISSUE THREAD

**Issue by epsilon-jpage** [puppetlabs/ruby-pwsh#51]
## Describe the Bug
When trying to use the xiisLogging class from the xWebAdministration module to reconfigure default IIS logging preferences such as log location it does not work.

## Expected Behavior
Expected the Default IIS Logging Location to be set to D:\inetpub\logs\LogFiles.

## Steps to Reproduce
In the Puppetfile I added ...
mod 'dsc-xwebadministration', '3.2.0-0-0'

In a test profile I wrote ...
dsc_xiislogging { "Set IIS Loging Options":
  ensure       => "present",
  dsc_logpath  => "D:\\inetpub\\logs\\LogFiles",
}

I received an error at line stating dsc_xiislogging was invalid and could not called.

## Environment
Windows Server 2019.
Puppet Enterprise 2019.8.1
dsc-xwebadministration 3.2.0-0-0

## Additional Context
The conversion of the xWebAdministration module to this new puppet dsc module format appears to be quite buggy and the documentation is quite poor.

**Comment by michaeltlombardi** [comment]
As with your other issue, you do not want to specify the `ensure` keyword. All of the properties you are sending to DSC are _always_ prepended with `dsc_`.

In this case, you're also missing the non-optional property [`dsc_logcustomfields`](https://forge.puppet.com/dsc/xwebadministration/reference#dsc_logcustomfields). You can determine which properties are optional and not via the type reference documentation or the hover help if you have the VSCode extension installed.

**Comment by epsilon-jpage** [comment]
@michaeltlombardi  How do you write dsc_logcustomfields ?  The documentation you linked doesn't give a good example and I've tried ...dsc_logcustomfields => [ "RequestHeader", "X-Forwarded-For", "X-Forwarded-For" ]
and that doesn't work.  All I want to do is change the default IIS log path.

**Comment by michaeltlombardi** [comment]
`dsc_logcustomfields` has the following type definition:

```
Array[Struct[{ SourceType => Enum['RequestHeader', 'ResponseHeader', 'ServerVariable'], SourceName => String, Ensure => Optional[Enum['Present', 'Absent']], LogFieldName => String }]]
# Expanded for easier readability
Array[
  Struct[{
    SourceType => Enum['RequestHeader', 'ResponseHeader', 'ServerVariable'],
    SourceName => String,
    Ensure => Optional[Enum['Present', 'Absent']],
    LogFieldName => String
  }]
]
```

which you would represent in a Puppet manifest like so:

```puppet
dsc_logcustomfields => [{
  SourceType   => 'RequestHeader',
  SourceName   => 'Foo',
  LogFieldName => 'Bar',
}],
#Example with two custom fields
dsc_logcustomfields => [
  {
    SourceType   => 'RequestHeader',
    SourceName   => 'Foo',
    LogFieldName => 'Bar',
  },
  {
    SourceType   => 'ResponseHeader',
    SourceName   => 'Baz',
    LogFieldName => 'Qux',
  }
],
```

Looking at the type definition and comparing to the DSC resource, it _does_ look like you've uncovered a bug, but it's in the builder, not this project. It appears that the nested CIM parsing does not properly mark optional CIM instances when they're arrays. I'll file a bug there referencing this issue, thanks!
