### ISSUE TITLE
xWebAdministration xWebSite

### ISSUE THREAD

**Issue by epsilon-jpage** [puppetlabs/ruby-pwsh#52]
## Describe the Bug
When trying to use the xWebSite class to remove the IIS Default Web Site from the xWebAdministration module it does not work.

## Expected Behavior
Default Application Pool should get removed.

## Steps to Reproduce
In the Puppetfile I added ...
mod 'dsc-xwebadministration', '3.2.0-0-0'

In a test profile I wrote ...
dsc_xwebapppool { "DefaultAppPool":
  ensure   => "Absent",
  dsc_name => "DefaultAppPool",
}

When there was nothing to remove, I received an invalid message stating the application pool was set to present (correction).  Everything else worked normally.

## Environment
Windows Server 2019.
Puppet Enterprise 2019.8.1
dsc-xwebadministration 3.2.0-0-0

## Additional Context
The conversion of the xWebAdministration module to this new puppet dsc module format appears to be quite buggy and the documentation is quite poor.

**Comment by michaeltlombardi** [comment]
The problem you've run into is both Puppet and DSC want to have ensure keywords. The documentation in the usage section directs you to only specify the `dsc_ensure` key, not the `ensure` key. That's the root of the behavior you're seeing here.

**Comment by epsilon-jpage** [comment]
That's fair, but the documentation does say dsc_xwebapppool supports ensure.

**Comment by michaeltlombardi** [comment]
Right, so you would use `dsc_ensure` - everything you pass to `Invoke-Dsc` is prefaced with `dsc_` - any other properties are for Puppet only.

**Comment by epsilon-jpage** [comment]
Then the documentation should either be corrected or clarified at some point given the obvious generic nature of all the documentation.

**Comment by michaeltlombardi** [comment]
I'll file an issue for a clarification of the documentation in [puppetlabs/Puppet.Dsc](https://github.com/puppetlabs/Puppet.Dsc) to update the auto-docs; would you mind being pinged on the PR for that issue as a reviewer?

**Comment by epsilon-jpage** [comment]
Yes, I'll help.
